First pass at 'infrastructure' :).
That is, a working pre-commit hook, tracked in the repository, and
instructions for how to use the repository (including how to install the
pre-commit hook).

diff --git a/.samuel_skean_dotfiles_miscellanea/git_hooks/pre-commit b/.samuel_skean_dotfiles_miscellanea/git_hooks/pre-commit
--- a/.samuel_skean_dotfiles_miscellanea/git_hooks/pre-commit
+++ b/.samuel_skean_dotfiles_miscellanea/git_hooks/pre-commit
@@ -1,9 +1,11 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # An example hook script to verify what is about to be committed.
 # Called by "git commit" with no arguments.  The hook should
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
+
+set -eu
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -14,7 +16,8 @@ else
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --type=bool hooks.allownonascii)
+#
+allownonascii=$(git config --type=bool hooks.allownonascii || true) # Slight modification of the template (adding `|| true`) so script doesn't immediately fail under `set -e`.
 
 # Redirect output to stderr.
 exec 1>&2
@@ -41,6 +44,17 @@ If you know what you are doing you can disable this check using:
   git config hooks.allownonascii true
 EOF
 	exit 1
+fi
+
+# MAIN ADDITION:
+
+echo 'FIXME: This hook currently only examines the working tree for my purposes, not staged data.'
+
+# Note that this is hardcoded to look at `${HOME}`, not wherever this repo is "checked-out", because this is a bare git repo.
+# Thankfully this is for my dotfiles, so they better be in ${HOME}!
+if ! diff <(sed -n '/^# Should be alpha/, $p' "${HOME}/.gitignore" | grep --invert-match '^#') <(sed -n '/^# Should be alpha/, $p' "${HOME}/.gitignore" | grep --invert-match '^#' | sort); then
+    echo 'Alphabetize the items at the end of  `~/.gitignore` according to the output of diff printed above.'
+    exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
